[build]
rustc-wrapper = "sccache"
# .cargo/config.toml
[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-cpu=native"
]

# Cross-compilation target for Raspberry Pi 5 (ARM64)
[target.aarch64-unknown-linux-gnu]
# Native cross-compilation using Homebrew toolchain
linker = "aarch64-unknown-linux-gnu-gcc"


